{
    "DESIGN_NAME": "WB_RAM2K",
    "VERILOG_FILES": "dir::/rtl/*.sv",
    "CLOCK_PERIOD": 100, 
    "CLOCK_PORT": "clk_i",
    "FP_PDN_SKIPTRIM": true,
    "RUN_POST_GRT_RESIZER_TIMING": true,
    "RUN_POST_GRT_DESIGN_REPAIR": true,
    "SYNTH_AUTONAME": true, 

    # Die Area Sizing
    "FP_SIZING": "absolute",
    "DIE_AREA": [0, 0, 1600, 1600],

    "VDD_NETS": [
        "VPWR"
    ],
    "GND_NETS": [
        "VGND"
    ],

    "MACROS": {
      "DFFRAM256x32": {
          "instances": {
          "RAM_1": {
              "location": [150, 200], 
              "orientation": "N" 
          },
          "RAM_2": {
              "location": [150, 850],
              "orientation": "N"
          }
        },
        "gds": [
            "dir::macros/dffram256x32/layout/gds/DFFRAM256x32.gds"
        ],
        "lef": [
            "dir::macros/dffram256x32/layout/lef/DFFRAM256x32.lef"
        ],
        "spef": { 
            "max*": [
            "dir::macros/dffram256x32/timing/spef/DFFRAM256x32.max.spef" 
            ],
            "min*": [
            "dir::macros/dffram256x32/timing/spef/DFFRAM256x32.min.spef" 
            ],
            "nom*": [
            "dir::macros/dffram256x32/timing/spef/DFFRAM256x32.nom.spef" 
            ]
        },
        "lib": { 
            "*": [
                "dir::macros/dffram256x32/timing/lib/max/DFFRAM256x32.Slowest.lib"
            ]
        },
        "nl": [ 
        "dir::macros/dffram256x32/hdl/gl/DFFRAM256x32.v"
        ],
        "pnl": [ 
        "dir::macros/dffram256x32/hdl/gl/DFFRAM256x32.v"
        ]
      }
    },
   
    # MACRO POWER NETS
    "PDN_MACRO_CONNECTIONS": [
        "RAM_1 VPWR VGND VPWR VGND",
        "RAM_2 VPWR VGND VPWR VGND"
    ],

    # PDN
    "FP_PDN_VOFFSET": 5,
    "FP_PDN_HOFFSET": 5,
    "FP_PDN_VWIDTH": 3.1,
    "FP_PDN_HWIDTH": 3.1,
    "FP_PDN_VSPACING": 15.5,
    "FP_PDN_HSPACING": 15.5,
    "FP_PDN_VPITCH": 100,
    "FP_PDN_HPITCH": 100,

    # PDN Ring 
    "FP_PDN_CORE_RING": true,
    "FP_PDN_CORE_RING_VWIDTH": 3.1,
    "FP_PDN_CORE_RING_HWIDTH": 3.1,
    "FP_PDN_CORE_RING_VOFFSET": 12.45,
    "FP_PDN_CORE_RING_HOFFSET": 12.45,
    "FP_PDN_CORE_RING_VSPACING": 1.7,
    "FP_PDN_CORE_RING_HSPACING": 1.7,

    # Antennae Violations 
    "PL_RESIZER_ALLOW_SETUP_VIOS": true,
    "GRT_RESIZER_ALLOW_SETUP_VIOS": true,
    "GRT_ANTENNA_ITERS": 15,
    "GRT_ANTENNA_MARGIN": 15,
    "RUN_HEURISTIC_DIODE_INSERTION": true,
    "DESIGN_REPAIR_MAX_WIRE_LENGTH": 800,
    "PL_WIRE_LENGTH_COEF": 0.05,
    "RUN_POST_GRT_DESIGN_REPAIR": true,
    "DESIGN_REPAIR_MAX_SLEW_PCT": 30,
    "DESIGN_REPAIR_MAX_CAP_PCT": 30,
    "MAX_TRANSITION_CONSTRAINT": 1.5
}